### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by theodorosploumis** [theodorosploumis/php-docs#1]
- [ ] Multiple url list
- [ ] Easy internal reference option
- [ ] Taxonomy pages
- [ ] Annotations on images
- [ ] Screencast field
- [ ] TOC link on bottom of every page
- [ ] prev/next links
- [ ] Check Drupal modules: https://www.drupal.org/project/cg
